[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/sitemap.xml"
  to = "https://yynlzhfibeozrwrtrjbs.supabase.co/functions/v1/sitemap"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "https://yynlzhfibeozrwrtrjbs.supabase.co/functions/v1/robots"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
