// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yynlzhfibeozrwrtrjbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5bmx6aGZpYmVvenJ3cnRyamJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjg2MTUsImV4cCI6MjA2MjY0NDYxNX0.2ASPm5tNWrcOU1SGwO0Ob_uS9Jwyt10z2AwRm5MuXkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);